### ISSUE TITLE
healthcheck endpoint

### ISSUE THREAD

**Issue by Revolution1** [alt-research/subway#21]
support healthcheck endpoint like
HTTP Get `/health` or `/healthz`

**Comment by koushiro** [comment]
It has been supported. Do we need to close this issue?

```
  server:
    port: 9944
    listen_address: '0.0.0.0'
    max_connections: 2000
    max_batch_size: 10
    http_methods:
      - path: /health
        method: system_health
      - path: /liveness
        method: chain_getBlockHash
```
